# Generated by Django 2.0.2 on 2018-03-08 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField(max_length=400)),
                ('author_name', models.CharField(max_length=40)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('color', models.CharField(choices=[('#eaadaa', 'Red'), ('#c9e2ee', 'Blue'), ('#fbf5c5', 'Yellow'), ('#bfe5ac', 'Green'), ('#FFE0B1', 'Orange'), ('#C0B4E7', 'Purple'), ('#FFFFFF', 'White')], default='#FFFFFF', max_length=7)),
            ],
        ),
    ]
