# Generated by Django 2.0.2 on 2018-03-06 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0003_auto_20180304_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('#eaadaa', 'Red'), ('#c9e2ee', 'Blue'), ('#fbf5c5', 'Yellow'), ('#bfe5ac', 'Green'), ('#FFE0B1', 'Orange'), ('#C0B4E7', 'Purple'), ('#FFFFFF', 'White')], default='#FFFFFF', max_length=7),
        ),
    ]
